[package]
name = "tardi-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[features]
int-word = ["tardi/int-word"]

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }

[dependencies.tardi]
path = ".."

[[bin]]
name = "fuzz_target_f32"
path = "fuzz_targets/fuzz_target_f32.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_i32"
path = "fuzz_targets/fuzz_target_i32.rs"
test = false
doc = false
bench = false
required-features = ["int-word"]
